export const EDUCATION_OPTIONS = [
  { label: "Diploma (D1-D4)", value: "diploma" },
  { label: "Sarjana (S1)", value: "bachelor" },
  { label: "Magister (S2)", value: "master" },
  { label: "Doktor (S3)", value: "phd" },
];

export const PREFIX_OPTIONS = [
  { label: "-", value: "" },
  { label: "Dr.", value: "Dr." },
  { label: "Drg.", value: "Drg." },
  { label: "H.", value: "H." },
  { label: "Hj.", value: "Hj." },
  { label: "Ir.", value: "Ir." },
  { label: "Prof.", value: "Prof." },
  { label: "Prof. Dr.", value: "Prof. Dr." },
];

export const SUFFIX_OPTIONS = [
  { label: "-", value: "" },
  { label: "A.Md.", value: "A.Md." },
  { label: "A.Md.Keb.", value: "A.Md.Keb." },
  { label: "A.Md.Kep.", value: "A.Md.Kep." },
  { label: "A.Md.T.", value: "A.Md.T." },
  { label: "S.Ak.", value: "S.Ak." },
  { label: "S.A.P.", value: "S.A.P." },
  { label: "S.Ars.", value: "S.Ars." },
  { label: "S.Ds.", value: "S.Ds." },
  { label: "S.E.", value: "S.E." },
  { label: "S.Farm.", value: "S.Farm." },
  { label: "S.H.", value: "S.H." },
  { label: "S.Hum.", value: "S.Hum." },
  { label: "S.I.Kom.", value: "S.I.Kom." },
  { label: "S.Ked.", value: "S.Ked." },
  { label: "S.Kep.", value: "S.Kep." },
  { label: "S.Kom.", value: "S.Kom." },
  { label: "S.P.", value: "S.P." },
  { label: "S.Pd.", value: "S.Pd." },
  { label: "S.Psi.", value: "S.Psi." },
  { label: "S.S.", value: "S.S." },
  { label: "S.Si.", value: "S.Si." },
  { label: "S.Sos.", value: "S.Sos." },
  { label: "S.T.", value: "S.T." },
  { label: "S.Tr.", value: "S.Tr." },
  { label: "M.A.", value: "M.A." },
  { label: "M.Ak.", value: "M.Ak." },
  { label: "M.B.A.", value: "M.B.A." },
  { label: "M.Cs.", value: "M.Cs." },
  { label: "M.Kes.", value: "M.Kes." },
  { label: "M.Kom.", value: "M.Kom." },
  { label: "M.M.", value: "M.M." },
  { label: "M.Pd.", value: "M.Pd." },
  { label: "M.Psi.", value: "M.Psi." },
  { label: "M.Sc.", value: "M.Sc." },
  { label: "M.Si.", value: "M.Si." },
  { label: "M.T.", value: "M.T." },
  { label: "Dr.", value: "Dr." },
  { label: "Ph.D.", value: "Ph.D." },
];